version: '3.1'
services:
  db:
    image: postgres
    container_name: db-senior
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9998:8080

  backend:
    image: openjdk:17-oracle
    container_name: backend-senior
    hostname: backend-assemblies
    restart: unless-stopped
    volumes:
      - ./target/senior-0.0.1-SNAPSHOT.jar:/opt/senior-0.0.1-SNAPSHOT.jar
    environment:
      - TZ=America/Sao_Paulo
      - DB_HOST=db
    depends_on:
      - db   
    ports:
      - 8080:8080
    entrypoint:
      - "java"
      - "-server"
      - "-jar"
      - "/opt/senior-0.0.1-SNAPSHOT.jar"